version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
